# 1-1 Affine Functions with 1 Feature

## Code.1-1-1:Affine Function

- Tip : 텐서플로우는 기본적으로 부동소수점(Floating-poin) 32bit 기준으로 움직여서 숫자를 넣을 때 .을 써주는 습관을 들이는게 좋다. 
ex) 10. , 20.

In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

# input setting (Note: input -> matrix)
x = tf.constant([[10.]])  # vector가 아니라 matrix형태로 만들었다.
# print(x.shape)  # matrix확인용

# imp. an affine function
dense = Dense(units=1, activation='linear') # unit 1개로 affine function 한개를 만들 수 있다.
                                            # activation은 linear로 정함(sigmoid, tanh, relu)
# forward propagation + params initialization
y_tf = dense(x) # tensorflow는 윗줄 코드에서 w,b를 초기화를 시키지 않아서 지금 코드처럼 x값이 들어갈 때 초기화 진행

W, B = dense.get_weights()  # weight와 bias 추출
# print(W, B) # W, B 확인용

# forward propagation(manual)
y_man = tf.linalg.matmul(x, W) + B  # 행렬 곱 matmul
                                    # z(y) = x * W + B 확인
# print results
print('===== Input/Weight/Bias =====')
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('W: {}\n{}\n'.format(W.shape, W))
print('B: {}\n{}\n'.format(B.shape, B))

print('===== Outputs =====')
print('y(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y(Manual): {}\n{}\n'.format(y_man.shape, y_man.numpy()))

===== Input/Weight/Bias =====
x: (1, 1)
[[10.]]

W: (1, 1)
[[-0.11011887]]

B: (1,)
[0.]

===== Outputs =====
y(Tensorflow): (1, 1)
[[-1.1011887]]

y(Manual): (1, 1)
[[-1.1011887]]



## Code.1-1-1:Params Initialization

In [2]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]])

# weight/bias setting
w, b = tf.constant(10.), tf.constant(20.)
#print(w, b)
w_init, b_init = Constant(w), Constant(b)
#print(w_init, b_init)

# imp. an affine function
dense = Dense(units=1, activation='linear', kernel_initializer=w_init, bias_initializer=b_init)

y_tf = dense(x)
print(y_tf) # y = x(10) * w(10) + b(20) = 120이 나온다.
W, B = dense.get_weights()

#print results
print('W: {}\n{}\n'.format(W.shape, W))
print('B: {}\n{}\n'.format(B.shape, B))

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W: (1, 1)
[[10.]]

B: (1,)
[20.]



# 1-2 Affine Functions with n Features

## Code.1-2-1:Affine Functions with n Features

In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10) # minvalue=0, minvalue=10이여서 0~10 사이 랜덤값
print(x.shape, '\n', x) # 실행할때마다 random때문에 값이 계속 바뀜

dense = Dense(units=1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

# print results
print('===== Input/Weight/Bias =====')
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('W: {}\n{}\n'.format(W.shape, W)) # column vector로 만들어짐
print('B: {}\n{}\n'.format(B.shape, B)) # bias는 스칼라값 하나

print('===== Outputs =====')
print('y(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y(Manual): {}\n{}\n'.format(y_man.shape, y_man.numpy()))

(1, 10) 
 tf.Tensor(
[[6.982216   0.778625   6.4175835  7.5722313  0.46729088 4.347106
  0.4093325  6.3379297  0.13846755 7.043124  ]], shape=(1, 10), dtype=float32)
===== Input/Weight/Bias =====
x: (1, 10)
[[6.982216   0.778625   6.4175835  7.5722313  0.46729088 4.347106
  0.4093325  6.3379297  0.13846755 7.043124  ]]

W: (10, 1)
[[ 0.49675232]
 [ 0.7365208 ]
 [ 0.31463128]
 [-0.35472855]
 [ 0.64598984]
 [-0.31196147]
 [-0.5374459 ]
 [ 0.65382725]
 [-0.52133197]
 [-0.1829465 ]]

B: (1,)
[0.]

===== Outputs =====
y(Tensorflow): (1, 1)
[[4.8839417]]

y(Manual): (1, 1)
[[4.8839417]]

