# 3-4 Softmax Layers

## Code.3-4-1:Input,Output of Softmax

In [4]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape=(2, 5), minval=-10, maxval=10)
print(logit)

softmax_value = Activation('softmax')(logit)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)

print("Logits: \n", logit.numpy())
print("Probabilities: \n", softmax_value.numpy())
print("Sum of softmax values: \n", softmax_sum)

tf.Tensor(
[[-9.603922   5.9750385  1.7868471  6.00609    8.890284 ]
 [-9.857903  -5.4626155 -8.254997   2.616949   2.9742737]], shape=(2, 5), dtype=float32)
Logits: 
 [[-9.603922   5.9750385  1.7868471  6.00609    8.890284 ]
 [-9.857903  -5.4626155 -8.254997   2.616949   2.9742737]]
Probabilities: 
 [[8.3635108e-09 4.8780378e-02 7.4017892e-04 5.0318848e-02 9.0016055e-01]
 [1.5727672e-06 1.2750087e-04 7.8126322e-06 4.1155100e-01 5.8831209e-01]]
Sum of softmax values: 
 tf.Tensor([0.99999994 1.        ], shape=(2,), dtype=float32)


## Code.3-4-2: Softmax in Dense Layers

In [7]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape=(8, 5), minval=-10, maxval=10)
dense = Dense(units=8, activation='softmax')  # softmax는 마지막 layer에서 작동함

Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor(
[1.         1.         1.         1.         0.9999999  0.9999999
 0.9999999  0.99999994], shape=(8,), dtype=float32)


# 3-5: Multi-class Classifiers

## Code.3-5-1: Multi-class Classifiers

In [11]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=8, activation='relu')
    self.dense2 = Dense(units=5, activation='relu')
    self.dense3 = Dense(units=3, activation='softmax')

  def call(self, x):
    print("X: {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense1(x)
    print("A1: {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense2(x)
    print("A2: {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense3(x)
    print("Y: {}\n{}\n".format(x.shape, x.numpy())) # Probability
    print("Sum of vectors: {}\n".format(tf.reduce_sum(x, axis=1)))
    return x

model = TestModel()

X = tf.random.uniform(shape=(8,5), minval=-10, maxval=10)
Y = model(X)

X: (8, 5)
[[-5.0341153 -9.783651   4.4141693 -8.594229  -1.0706234]
 [-7.8588057  6.450268   4.7823095  3.480854  -5.3580832]
 [ 3.0438614  6.694706   9.048031  -4.525492  -4.1047096]
 [ 7.9837265  1.0298996  6.0813503  9.702606  -7.1006823]
 [-3.8169622 -6.033051  -7.6539683  4.456751   8.063068 ]
 [-6.550176  -8.512759  -4.7449923 -9.307489   2.5713425]
 [ 6.955658  -2.9118276  2.2111301 -0.3485222 -2.426753 ]
 [ 8.866352   0.9312105 -7.0905256 -8.845026   6.46826  ]]

A1: (8, 8)
[[ 0.          2.321697    0.          0.          8.191627    9.88234
   0.          0.        ]
 [ 5.697619    8.864868    0.          0.          0.16788012  0.
   0.          0.        ]
 [ 7.3701363   2.2928932   0.          2.5605617   0.          0.
   0.          1.6151679 ]
 [ 4.772511    5.454235    0.          0.          0.          0.
   2.0255733   9.309228  ]
 [ 0.          0.          6.934877    0.          1.6145505   5.340133
   3.5618227   0.        ]
 [ 0.          0.          2.6474109 